---
- hosts: web
  remote_user: root
  tasks:
    - shell: mkdir /tmp/cache
      ignore_errors: True
    - copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: 0644
      tags: webconf
      notify:
        - reload webserver
  handlers:
    - name: reload webserver
      service:
        name: httpd
        state: restarted
